name: firebase_messaging_platform_interface
description: A common platform interface for the firebase_messaging plugin.
version: 4.5.46
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_messaging/firebase_messaging_platform_interface
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_messaging/firebase_messaging_platform_interface

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals:
    git:
      url: https://github.com/vudvv/_flutterfire_internals.git
      ref: v1.3.45
  firebase_core:
    git:
      url: https://github.com/vudvv/firebase_core.git
      ref: v3.6.1
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface: ^5.3.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
